development:
  facebook_key: "327114094161321"
  facebook_secret: "142f1d6d6d5de2186cb227dd51e5ee6b"

  twitter_key: "xOAHAlsH83xENwwentv9BEnCx"
  twitter_secret: "IpEgMrrEgzo7nVV5634iyKFhU0tHdQlzxdrdOw6HUPNhgfkDRA"

  github_key: "24c5bf6f2c2f169c9033"
  github_secret: "4a5c81f6c21cebaf054006dca8ac59cb345b8665"

  linkedin_key: "77rtffdk0a5y4m"
  linkedin_secret: "G2rpZxx79CTs8rKX"

  google_key: "906080259768-s3situukklfkhsrjh6p43p5d36oj9s3u.apps.googleusercontent.com"
  google_secret: "ds1qcaP2hoDYCNTLRPeJwNRt"

production:
  facebook_key: "327114094161321"
  facebook_secret: "142f1d6d6d5de2186cb227dd51e5ee6b"

  twitter_key: "xOAHAlsH83xENwwentv9BEnCx"
  twitter_secret: "IpEgMrrEgzo7nVV5634iyKFhU0tHdQlzxdrdOw6HUPNhgfkDRA"

  github_key: "24c5bf6f2c2f169c9033"
  github_secret: "4a5c81f6c21cebaf054006dca8ac59cb345b8665"

  linkedin_key: "77rtffdk0a5y4m"
  linkedin_secret: "G2rpZxx79CTs8rKX"

  google_key: "906080259768-s3situukklfkhsrjh6p43p5d36oj9s3u.apps.googleusercontent.com"
  google_secret: "ds1qcaP2hoDYCNTLRPeJwNRt"
