require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe CarouselsController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # Carousel. As you add validations to Carousel, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CarouselsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all carousels as @carousels" do
      carousel = Carousel.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:carousels)).to eq([carousel])
    end
  end

  describe "GET show" do
    it "assigns the requested carousel as @carousel" do
      carousel = Carousel.create! valid_attributes
      get :show, {:id => carousel.to_param}, valid_session
      expect(assigns(:carousel)).to eq(carousel)
    end
  end

  describe "GET new" do
    it "assigns a new carousel as @carousel" do
      get :new, {}, valid_session
      expect(assigns(:carousel)).to be_a_new(Carousel)
    end
  end

  describe "GET edit" do
    it "assigns the requested carousel as @carousel" do
      carousel = Carousel.create! valid_attributes
      get :edit, {:id => carousel.to_param}, valid_session
      expect(assigns(:carousel)).to eq(carousel)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Carousel" do
        expect {
          post :create, {:carousel => valid_attributes}, valid_session
        }.to change(Carousel, :count).by(1)
      end

      it "assigns a newly created carousel as @carousel" do
        post :create, {:carousel => valid_attributes}, valid_session
        expect(assigns(:carousel)).to be_a(Carousel)
        expect(assigns(:carousel)).to be_persisted
      end

      it "redirects to the created carousel" do
        post :create, {:carousel => valid_attributes}, valid_session
        expect(response).to redirect_to(Carousel.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved carousel as @carousel" do
        post :create, {:carousel => invalid_attributes}, valid_session
        expect(assigns(:carousel)).to be_a_new(Carousel)
      end

      it "re-renders the 'new' template" do
        post :create, {:carousel => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested carousel" do
        carousel = Carousel.create! valid_attributes
        put :update, {:id => carousel.to_param, :carousel => new_attributes}, valid_session
        carousel.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested carousel as @carousel" do
        carousel = Carousel.create! valid_attributes
        put :update, {:id => carousel.to_param, :carousel => valid_attributes}, valid_session
        expect(assigns(:carousel)).to eq(carousel)
      end

      it "redirects to the carousel" do
        carousel = Carousel.create! valid_attributes
        put :update, {:id => carousel.to_param, :carousel => valid_attributes}, valid_session
        expect(response).to redirect_to(carousel)
      end
    end

    describe "with invalid params" do
      it "assigns the carousel as @carousel" do
        carousel = Carousel.create! valid_attributes
        put :update, {:id => carousel.to_param, :carousel => invalid_attributes}, valid_session
        expect(assigns(:carousel)).to eq(carousel)
      end

      it "re-renders the 'edit' template" do
        carousel = Carousel.create! valid_attributes
        put :update, {:id => carousel.to_param, :carousel => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested carousel" do
      carousel = Carousel.create! valid_attributes
      expect {
        delete :destroy, {:id => carousel.to_param}, valid_session
      }.to change(Carousel, :count).by(-1)
    end

    it "redirects to the carousels list" do
      carousel = Carousel.create! valid_attributes
      delete :destroy, {:id => carousel.to_param}, valid_session
      expect(response).to redirect_to(carousels_url)
    end
  end

end
